export const DELETE_EVENT = "DELETE_EVENT";
export const CREATE_EVENT = "CREATE_EVENT";
export const DELETE_ALL_EVENTS = "DELETE_ALL_EVENTS";
export const Add_OPERATION_LOG = "Add_OPERATION_LOG";
export const DELETE_ALL_OPERATION_LOGS = "DELETE_ALL_OPERATION_LOGS";
